# Generated by Django 2.2 on 2021-04-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='image',
            field=models.ImageField(default='../kush.jpg', upload_to='doc_pro_pic'),
        ),
    ]
