# Generated by Django 2.2 on 2021-04-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210405_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescription',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
        ),
    ]
