# Generated by Django 2.2 on 2021-04-08 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
