# Generated by Django 2.2 on 2021-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../media/', upload_to='deoc_certi'),
        ),
    ]
